format = """
$directory\
$git_branch\
$git_status\
$line_break\
$username $character"""

[directory]
truncation_length = 8
truncation_symbol = '…/'

[git_branch]
symbol = ' '
truncation_length = 4
truncation_symbol = '…/'

ahead = '(+${count})'
behind = '(-${count})'

[username]
style_user = 'white'
style_root = 'cyan bold'
format = "[$user]($style)"
disabled = false
show_always = true
